import { FREE_SUBMIT_QUOTA, FREE_VIRTUAL_ATTEMPTS, PLAN_PRICING, REFUND_WINDOW_DAYS } from "@oj/shared";

type Copy = { "zh-TW": string; en: string };
export interface FaqItem { id: string; question: Copy; answer: Copy }
const item = (id: string, q: string, a: string, qEn: string, aEn: string): FaqItem => ({ id, question: { "zh-TW": q, en: qEn }, answer: { "zh-TW": a, en: aEn } });
export const SUPPORT_EMAIL = "judges0801@gmail.com";

/** The visible answers and search-engine structured data come from the same versioned copy. */
export const FAQ_SECTIONS: { id: string; title: Copy; items: FaqItem[] }[] = [
  { id: "start", title: { "zh-TW": "開始練習", en: "Getting started" }, items: [
    item("first-problem", "第一次使用，應該從哪裡開始？", "先到題庫依難度或主題挑一題，閱讀輸入輸出說明，試跑範例後再提交。不確定從哪裡下手，可以先看看題目集；首頁的一分鐘互動練習不需要登入，也不會消耗提交額度。", "Where should I start?", "Pick a problem by difficulty or topic, read its input and output requirements, and try the samples before submitting. Collections can help you choose a path. The homepage demo needs no account and uses no submission quota."),
    item("free-limits", "免費方案有哪些限制？額度何時重置？", `每個日曆月可提交 ${FREE_SUBMIT_QUOTA} 次程式碼、開始 ${FREE_VIRTUAL_ATTEMPTS} 場虛擬測驗，依臺灣時間每月 1 日重置。可在方案頁查看目前用量；重新整理或重複點擊同一筆尚未收到回應的提交，不應重複扣額度。`, "What are the Free limits and when do they reset?", `Free includes ${FREE_SUBMIT_QUOTA} submissions and ${FREE_VIRTUAL_ATTEMPTS} virtual exam per calendar month, resetting on the first day in Taiwan time. Check usage on the plan page. Retrying the same in-flight submission does not consume another quota.`),
    item("languages", "可以使用哪些程式語言？", "可選 C++、C、Python 與 Java。本機評測與外部 UVa 評測的編譯器版本可能不同；使用外部評測時請留意版本相容性。優先使用標準函式庫，並以題目頁列出的資源限制為準。", "Which programming languages are available?", "Choose C++, C, Python or Java. Local and external UVa judges may use different compiler versions, so check compatibility when using an external judge. Prefer standard libraries and follow the problem's resource limits."),
    item("pro-benefits", "Pro 適合什麼樣的使用者？", "Pro 提供不限次數的正式提交與虛擬測驗，並開放歷屆出題次數等進階資料。服務仍有合理的提交冷卻與資源限制，以維持所有人的評測品質。免費使用者也可瀏覽公開討論與排行榜。", "Who is Pro for?", "Pro removes the monthly submission and virtual-exam caps and unlocks data such as exam appearance counts. Cooldowns and resource safeguards still apply. Public discussions and leaderboards are also available to Free users."),
  ] },
  { id: "judge", title: { "zh-TW": "提交與評測", en: "Submissions and judging" }, items: [
    item("verdict", "AC、WA、TLE、CE、SE 是什麼意思？", "AC 表示通過該題目前的測試；WA 是答案不符；TLE 是超時；MLE 是超出記憶體限制；RE 是執行錯誤；CE 是編譯失敗；OLE 是輸出過多；PE 是格式差異；RF 是受限制操作；SE 是評測系統錯誤。通過測試不代表形式化證明程式在所有可能情況都正確。", "What do AC, WA, TLE, CE and SE mean?", "AC passes the current tests; WA is a wrong answer; TLE exceeds time; MLE exceeds memory; RE is a runtime error; CE is a compile error; OLE exceeds output limits; PE is a formatting difference; RF is a restricted operation; SE is a system error. Passing tests is not a formal proof for every possible input."),
    item("samples", "範例都過了，為什麼還是 WA？", "範例只呈現部分情況。再檢查最小與最大輸入、重複值、空集合、整數溢位、多筆資料、結尾換行與題目指定格式。自訂測試適合釐清程式行為，但不取代正式評測。", "Why do I get WA after passing the samples?", "Samples cover only a few cases. Check minimum and maximum inputs, duplicates, empty sets, integer overflow, multiple cases and output formatting. Custom tests help you understand behavior but do not replace judging."),
    item("cooldown", "為什麼要等 10 秒才能再次提交？", "提交有 10 秒冷卻，以避免誤觸重送與短時間大量工作排入評測。網路不穩時，請先查看提交紀錄，確認上一筆是否已經收到。", "Why is there a 10-second submission cooldown?", "The cooldown limits accidental duplicates and queue floods. If the connection is unstable, check your submission history before sending another solution."),
    item("pending", "評測一直停在 Pending 或 Judging，怎麼辦？", "頁面會接收即時結果，連線中斷時也會重新查詢已保存的狀態。可回到提交紀錄查看；系統會補送尚未排入佇列的工作。超過系統等待上限的提交會標為 SE，並依原提交月份退回額度。", "What if a submission stays Pending or Judging?", "The page receives live results and also retrieves saved status after connection interruptions. Check submission history; the system retries undispatched work. Submissions exceeding the system wait limit become SE, with quota returned to the original submission month."),
    item("se-quota", "系統錯誤會扣我的額度或測驗罰時嗎？", "SE 不應永久消耗提交額度；系統會以同一筆提交為單位退回一次。若月份已切換，不會扣減新月份的用量。新制測驗的 CE 與 SE 不計錯誤罰時，既有測驗紀錄保留原本計分版本。", "Do system errors consume quota or exam penalties?", "SE quota is returned once per submission. A refund for an earlier month does not reduce the new month's usage. New exam attempts exclude CE and SE from wrong-answer penalties; existing attempts keep their original scoring version."),
    item("ungradeable", "為什麼有些題目不能提交？", "題目需要本機隱藏測資或有效的外部評測對應，才能進行正式提交。尚未準備好的題目會停用提交；包含這類題目的虛擬測驗也不能開始，避免作答後才發現無法評分。", "Why can't I submit some problems?", "A problem needs local hidden tests or a valid external judge mapping. Submission is disabled until one is available. Exams containing an ungradeable problem cannot start."),
    item("judge-report", "我懷疑測資或評測有問題，該提供什麼？", `請聯絡 ${SUPPORT_EMAIL}，附上題目連結、提交編號、使用語言、預期結果，以及可重現的最小案例。請勿公開其他人的程式碼、隱藏測資或帳號密碼。`, "How do I report a judging issue?", `Email ${SUPPORT_EMAIL} with the problem link, submission ID, language, expected result and a minimal reproducible case. Do not share someone else's source, hidden tests or passwords.`),
  ] },
  { id: "exams", title: { "zh-TW": "虛擬測驗", en: "Virtual exams" }, items: [
    item("exam-start", "虛擬測驗從什麼時候開始計時？", "個人虛擬測驗在伺服器接受開始要求時建立作答時段；排定時間的場次則使用共同開始時間。開始前請確認題目數、考試長度與可使用的語言。", "When does the timer start?", "A personal virtual exam starts when the server accepts your start request. Scheduled exams share a fixed start time. Check the problem count, duration and languages before starting."),
    item("one-exam", "可以同時參加兩場測驗嗎？", "不可以。同一帳號只能有一個重疊的作答時段，開多個分頁也不會繞過限制。個人虛擬測驗可先提早結束，再開始另一場；已預約的排定場次也會檢查時間是否重疊。", "Can I take two exams at once?", "No. Each account may have only one overlapping attempt window, even across tabs. End a personal virtual attempt before starting another. Scheduled reservations are also checked for overlap."),
    item("exam-clock", "離開頁面、休眠或調整電腦時間，倒數會暫停嗎？", "不會。截止時間保存在伺服器，重新整理或換裝置會延續原時段。畫面會向伺服器校時；是否可交卷以伺服器收到提交時的時間為準，請避免壓在最後一秒送出。", "Does leaving the page or changing my clock pause the exam?", "No. The deadline is stored on the server and continues across reloads and devices. The display synchronizes with server time. Submission eligibility is decided when the server receives it, so avoid waiting until the final second."),
    item("exam-score", "成績與罰時如何計算？", "新制以解出題數優先，同分時罰時較少者優先。每題取首次 AC 的提交時間，經過分鐘數向下取整，加上首次 AC 前應計罰的錯誤次數乘以該場罰時設定。未解出題目不增加總罰時；CE 與 SE 不計錯誤罰時。", "How are scores and penalties calculated?", "New attempts rank by solved count, then lower penalty. Each solved problem uses the first AC submission time, rounded down to whole elapsed minutes, plus penalized wrong attempts before that AC times the exam's penalty setting. Unsolved problems add no total penalty; CE and SE are excluded."),
    item("late-result", "截止前已提交，但結果在時間到後才回來，會算分嗎？", "會，只要提交在伺服器允許的作答時段內成功受理並歸屬於該次測驗，就以提交時間計分。評測結果尚未回來時，成績可能仍會更新；平常練習的提交不會混入測驗紀錄。", "Does a result arriving after the deadline count?", "Yes, if the submission was accepted within the attempt window and belongs to that attempt. Scoring uses submission time. Results can still update while judging finishes. Practice submissions do not count toward an exam."),
    item("reattempt", "同一份歷屆試題可以重新測驗嗎？", "個人虛擬測驗在上一場結束後可重新開始，每次有獨立作答與成績紀錄，並會使用一次當月開考額度。排行榜顯示該場最佳嘗試；排定共同時間的場次不提供重新開始。", "Can I retake the same past exam?", "Personal virtual exams can be retaken after the previous attempt ends. Each has separate submissions and scores and consumes an exam start from the monthly quota. Standings show your best attempt. Scheduled exams cannot be restarted."),
  ] },
  { id: "billing", title: { "zh-TW": "訂閱、付款與退款", en: "Billing and refunds" }, items: [
    item("pricing", "Pro 的費用與付款方式是什麼？", `月方案 NT$${PLAN_PRICING.MONTHLY.amountNtd}、年方案 NT$${PLAN_PRICING.YEARLY.amountNtd}，採信用卡預付並自動續訂，實際金額以結帳確認頁為準。目前不提供 Apple Pay 或其他電子錢包；新購年方案不附加贈送天數。`, "How much does Pro cost and how can I pay?", `Monthly Pro is NT$${PLAN_PRICING.MONTHLY.amountNtd}; yearly Pro is NT$${PLAN_PRICING.YEARLY.amountNtd}. Credit-card subscriptions are prepaid and renew automatically; review the checkout total. Apple Pay and other wallets are not offered. New yearly purchases do not include bonus days.`),
    item("payment-delay", "付款成功後還顯示 Free，應該再付一次嗎？", `請先不要重複付款。回到方案頁重新整理，讓系統接收與核對金流通知；若超過 10 分鐘仍未更新，請寄信至 ${SUPPORT_EMAIL}，附上訂單編號、付款時間與金額，我們會核對交易。不要提供完整卡號、驗證碼或網銀密碼。`, "I paid but still see Free. Should I pay again?", `Please do not pay again. Refresh the plan page while the payment notification is verified. If nothing changes after 10 minutes, email ${SUPPORT_EMAIL} with your order ID, payment time and amount. Never send full card numbers, security codes or banking passwords.`),
    item("refund", "什麼情況可以申請全額退款？", `每個帳號的首次成功付款，可在付款成功後 ${REFUND_WINDOW_DAYS} 天（${REFUND_WINDOW_DAYS * 24} 小時）內於方案頁申請全額退款，限用一次。後續續扣不會重新產生退款期限；以畫面顯示的確切截止時間為準。舊交易若有原先承諾的條款，依該筆紀錄保留。`, "When can I request a full refund?", `The first successful purchase on each account may be fully refunded if requested within ${REFUND_WINDOW_DAYS} days (${REFUND_WINDOW_DAYS * 24} hours) after payment. This is available once per account; renewals do not reset the window. Use the exact deadline on the plan page. Earlier transactions retain their previously promised terms.`),
    item("refund-processing", "已申請退款，為什麼還沒收到錢？", "申請受理後會先停止相關續扣，再處理退刷。畫面會顯示處理中、待核對或完成；受理不等於銀行已入帳。實際帳單沖銷時間依發卡銀行而異。若顯示待核對，請保留申請編號聯絡支援，不需要反覆申請。", "Why hasn't a requested refund appeared on my card?", "The system stops the related subscription before processing the refund. The request shows processing, needs review or completed. Receipt of a request is not bank settlement; statement timing depends on your card issuer. Keep the request ID and contact support if review is needed."),
    item("cancel", "取消訂閱與退款有什麼差別？", "取消訂閱會停止未來自動續扣，已付費的使用權保留到到期日。退款則需符合首次付款期限，處理成功後會撤回該筆付款對應的使用權。即使已取消訂閱，只要仍符合期限，也可以申請首次付款退款。", "How is cancellation different from a refund?", "Cancellation stops future renewals while retaining already-paid access until expiry. A refund requires first-purchase eligibility and withdraws the access associated with that payment once processed. Cancelling does not remove an otherwise valid first-purchase refund window."),
    item("billing-date", "續扣日期為什麼和 Pro 到期日不同？", "續扣依原訂閱的日曆週期計算；短月份可能調整到月底。帳號若曾獲得其他使用權，Pro 到期日可能晚於下一次續扣日，兩者會分開顯示。", "Why can renewal and access expiry dates differ?", "Renewals follow the original subscription's calendar schedule, with short months clamped to month-end. Other access grants can extend Pro beyond the next renewal date, so these dates are displayed separately."),
  ] },
  { id: "account", title: { "zh-TW": "帳號、學校與通知", en: "Account, school and notifications" }, items: [
    item("login", "Google 登入與帳號密碼可以混用嗎？", "請使用建立帳號時的登入方式。系統不會只憑相同電子郵件就自動合併兩個登入身分；若無法登入，請聯絡支援核對帳號，不要將密碼或驗證信轉交他人。", "Can I switch between Google and password login?", "Use the method you used to create the account. Matching email addresses alone do not automatically link identities. Contact support if you cannot access your account; never share passwords or verification links."),
    item("password", "忘記密碼怎麼辦？", `Google 帳號請使用 Google 的帳號復原流程。若使用帳號密碼登入且無法存取，請聯絡 ${SUPPORT_EMAIL}，提供帳號名稱以開始身分核對；不要在信件中附上舊密碼。`, "What if I forget my password?", `For Google accounts, use Google's account recovery. For password-based accounts, contact ${SUPPORT_EMAIL} with your handle to begin identity verification. Do not include an old password.`),
    item("school-email", "學校驗證為什麼不能用一般 Gmail？", "學校驗證用來確認你能控制該校核可網域的信箱，因此一般個人信箱不適用。請在設定中選擇學校並使用所列的學校信箱；收到信後，以原帳號完成驗證。", "Why can't I verify my school with a personal Gmail address?", "School verification proves control of an address on an approved school email domain. Select your school in Settings and use the listed school mailbox, then complete verification with the original account."),
    item("school-missing", "找不到我的學校，或信箱網域不被接受，怎麼辦？", `請提供學校全名、實際信箱網域及學校官方的信箱說明連結至 ${SUPPORT_EMAIL}。學校清單與郵件網域需要分別核對，不會將官網網域直接視為學生信箱網域。`, "What if my school or email domain is missing?", `Send the school's full name, actual email domain and an official school email documentation link to ${SUPPORT_EMAIL}. School rosters and email domains require separate verification; website domains are not automatically treated as student email domains.`),
    item("verification-mail", "收不到驗證信怎麼辦？", "先檢查拼字、垃圾郵件、信箱容量與校方外部信件規則。等待重新寄送冷卻結束後再試，並使用最新一封信的連結。仍無法收到時，請聯絡支援；不需要提供信箱密碼。", "What if the verification email does not arrive?", "Check spelling, spam, mailbox capacity and school email policies. Retry after the resend cooldown and use the newest link. Contact support if delivery still fails; your mailbox password is never needed."),
    item("notifications", "打開通知就會把全部訊息標為已讀嗎？", "不會。可逐則按「標為已讀」，或開啟通知內的連結。只有明確按下「全部標為已讀」才會處理已載入狀態之前的通知；稍後抵達的新通知會保留未讀。通知中心可篩選未讀並載入更早紀錄。", "Does opening notifications mark everything as read?", "No. Mark an item individually or open its link. Only the explicit Mark all as read action marks notifications up to the displayed snapshot. Newer arrivals remain unread. The notification center offers unread filtering and earlier history."),
  ] },
];
