import java.io.BufferedInputStream;
import java.util.Arrays;

public class Main {
    static final int MOD=1000000009;static BufferedInputStream in=new BufferedInputStream(System.in);
    static long number()throws Exception{int c;do{c=in.read();}while(c>=0&&c<=32);long x=0;while(c>32){x=x*10+c-'0';c=in.read();}return x;}
    static int[] current,following,nextActive;static boolean[] seen;static int width,nextCount;
    static void transfer(int code,int shift,int lo,int hi,int flag){if(lo>hi)return;int target=(code&~(3<<shift))|(flag<<shift),window=0;for(int sum=0;sum<width;sum++){if(sum>=lo){window+=current[code*width+sum-lo];if(window>=MOD)window-=MOD;}if(sum>hi){window-=current[code*width+sum-hi-1];if(window<0)window+=MOD;}if(window!=0){int index=target*width+sum;following[index]+=window;if(following[index]>=MOD)following[index]-=MOD;if(!seen[target]){seen[target]=true;nextActive[nextCount++]=target;}}}}
    public static void main(String[] args)throws Exception{int cases=(int)number();int[] dp=new int[16384],active=new int[16384];nextActive=new int[16384];seen=new boolean[16384];current=new int[16384*19];following=new int[16384*19];for(int tc=1;tc<=cases;tc++){int n=(int)number(),prime=(int)number(),length=1;long[] lower=new long[n],upper=new long[n];for(int i=0;i<n;i++)lower[i]=number();for(int i=0;i<n;i++)upper[i]=number();int[][] ld=new int[n][64],ud=new int[n][64];for(int i=0;i<n;i++){long a=lower[i],b=upper[i];int count=0;do{ld[i][count]=(int)(a%prime);ud[i][count++]=(int)(b%prime);a/=prime;b/=prime;}while(b!=0);length=Math.max(length,count);}int states=1<<(2*n),initial=states-1;width=prime;Arrays.fill(dp,0,states,0);int activeCount=1;dp[initial]=1;active[0]=initial;
        for(int pos=length-1;pos>=0;pos--){Arrays.fill(current,0,states*width,0);for(int i=0;i<activeCount;i++)current[active[i]*width]=dp[active[i]];for(int coordinate=0;coordinate<n;coordinate++){Arrays.fill(following,0,states*width,0);Arrays.fill(seen,0,states,false);nextCount=0;int shift=2*coordinate,l=ld[coordinate][pos],u=ud[coordinate][pos];for(int i=0;i<activeCount;i++){int code=active[i],flag=code>>shift&3;if(flag==0)transfer(code,shift,0,prime-1,0);else if(flag==1){transfer(code,shift,l,l,1);transfer(code,shift,l+1,prime-1,0);}else if(flag==2){transfer(code,shift,0,u-1,0);transfer(code,shift,u,u,2);}else if(l==u)transfer(code,shift,l,l,3);else{transfer(code,shift,l,l,1);transfer(code,shift,l+1,u-1,0);transfer(code,shift,u,u,2);}}int[] swap=current;current=following;following=swap;swap=active;active=nextActive;nextActive=swap;activeCount=nextCount;}Arrays.fill(dp,0,states,0);for(int i=0;i<activeCount;i++){int code=active[i];for(int sum=0;sum<width;sum++){dp[code]+=current[code*width+sum];if(dp[code]>=MOD)dp[code]-=MOD;}}}
        int answer=0;for(int i=0;i<activeCount;i++){answer+=dp[active[i]];if(answer>=MOD)answer-=MOD;}System.out.println("Case "+tc+": "+answer);
    }}
}
