/**
 * Canonical list of Taiwan universities/colleges a user can attach to their profile — deliberately
 * a closed set (not free text) so the same institution always appears under one exact name,
 * which is what makes leaderboard filtering by school actually work. Both the profile-setup UI
 * (a searchable picker) and the backend (updateProfileSchema) validate against this same list.
 */
export const TAIWAN_UNIVERSITIES = [
  // National — comprehensive / research
  "國立臺灣大學",
  "國立清華大學",
  "國立陽明交通大學",
  "國立成功大學",
  "國立政治大學",
  "國立中央大學",
  "國立中山大學",
  "國立中興大學",
  "國立臺灣師範大學",
  "國立臺灣科技大學",
  "國立臺北科技大學",
  "國立臺北大學",
  "國立中正大學",
  "國立彰化師範大學",
  "國立高雄師範大學",
  "國立東華大學",
  "國立暨南國際大學",
  "國立宜蘭大學",
  "國立聯合大學",
  "國立高雄大學",
  "國立屏東大學",
  "國立嘉義大學",
  "國立臺南大學",
  "國立臺北教育大學",
  "國立臺東大學",
  "國立金門大學",
  "國立臺灣海洋大學",
  "國防醫學院",
  "國立中央警察大學",
  "國立空中大學",

  // National — technical / vocational
  "國立雲林科技大學",
  "國立虎尾科技大學",
  "國立高雄科技大學",
  "國立臺中科技大學",
  "國立勤益科技大學",
  "國立屏東科技大學",
  "國立臺北商業大學",
  "國立澎湖科技大學",
  "國立高雄餐旅大學",

  // National — arts / sports
  "國立臺北藝術大學",
  "國立臺灣藝術大學",
  "國立臺南藝術大學",
  "國立體育大學",
  "國立臺灣體育運動大學",

  // Private — comprehensive
  "輔仁大學",
  "東吳大學",
  "淡江大學",
  "中原大學",
  "逢甲大學",
  "東海大學",
  "靜宜大學",
  "銘傳大學",
  "中國文化大學",
  "世新大學",
  "實踐大學",
  "長庚大學",
  "元智大學",
  "義守大學",
  "中華大學",
  "玄奘大學",
  "佛光大學",
  "南華大學",
  "開南大學",
  "華梵大學",
  "長榮大學",
  "康寧大學",
  "亞洲大學",
  "大葉大學",
  "明道大學",

  // Private — medical
  "台北醫學大學",
  "高雄醫學大學",
  "中山醫學大學",
  "中國醫藥大學",
  "慈濟大學",
  "元培醫事科技大學",

  // Private — technical / vocational
  "朝陽科技大學",
  "南台科技大學",
  "崑山科技大學",
  "龍華科技大學",
  "明志科技大學",
  "文藻外語大學",
  "中臺科技大學",
  "弘光科技大學",
  "嶺東科技大學",
  "僑光科技大學",
  "台南應用科技大學",
  "德明財經科技大學",
  "致理科技大學",
  "醒吾科技大學",
  "中國科技大學",
  "東南科技大學",
  "中州科技大學",
  "修平科技大學",
  "遠東科技大學",
  "建國科技大學",
  "樹德科技大學",
  "正修科技大學",
  "高苑科技大學",
  "環球科技大學",

  // Catch-all for anyone whose school genuinely isn't on this list yet
  "其他",
] as const;

export type TaiwanUniversity = (typeof TAIWAN_UNIVERSITIES)[number];
