/** Generated from the reviewed catalog; never derive email authority from a website alone. */
export const SCHOOL_CATALOG_VERIFIED_AT = "2026-09-13";
export const SCHOOL_CATALOG_ACADEMIC_YEAR = 115;
export const SCHOOL_CATALOG_SOURCE = "https://depart.moe.edu.tw/ed4500/News_Content.aspx?n=63F5AB3D02A8BBAC&s=52D3798D5069E231&sms=1FF9979D10DBF9F3";
export const SCHOOL_NAME_ALIASES: Readonly<Record<string, string>> = {"台北醫學大學": "臺北醫學大學", "南台科技大學": "南臺科技大學", "高苑科技大學": "台鋼科技大學", "遠東科技大學": "中信科技大學", "國防醫學院": "國防醫學大學", "國立中央警察大學": "中央警察大學", "輔仁大學學校財團法人輔仁大學": "輔仁大學", "淡江大學學校財團法人淡江大學": "淡江大學", "中華大學學校財團法人中華大學": "中華大學", "華梵學校財團法人華梵大學": "華梵大學", "南臺學校財團法人南臺科技大學": "南臺科技大學", "嘉藥學校財團法人嘉南藥理大學": "嘉南藥理大學", "慈濟學校財團法人慈濟大學": "慈濟大學", "明新學校財團法人明新科技大學": "明新科技大學", "健行學校財團法人健行科技大學": "健行科技大學", "正修學校財團法人正修科技大學": "正修科技大學", "萬能學校財團法人萬能科技大學": "萬能科技大學", "台鋼學校財團法人台鋼科技大學": "台鋼科技大學", "台南家專學校財團法人台南應用科技大學": "台南應用科技大學", "中信金學校財團法人中信科技大學": "中信科技大學", "光宇學校財團法人元培醫事科技大學": "元培醫事科技大學", "中華學校財團法人中華科技大學": "中華科技大學", "廣亞學校財團法人育達科技大學": "育達科技大學", "美和學校財團法人美和科技大學": "美和科技大學", "修平學校財團法人修平科技大學": "修平科技大學", "長庚學校財團法人長庚科技大學": "長庚科技大學", "城市學校財團法人臺北城市科技大學": "臺北城市科技大學", "大華學校財團法人敏實科技大學": "敏實科技大學", "醒吾學校財團法人醒吾科技大學": "醒吾科技大學", "文藻學校財團法人文藻外語大學": "文藻外語大學", "華夏學校財團法人華夏科技大學": "華夏科技大學", "致理學校財團法人致理科技大學": "致理科技大學", "康寧學校財團法人康寧大學": "康寧大學", "宏國學校財團法人宏國德霖科技大學": "宏國德霖科技大學", "崇右學校財團法人崇右影藝科技大學": "崇右影藝科技大學", "台北海洋學校財團法人台北海洋科技大學": "台北海洋科技大學", "亞東學校財團法人亞東科技大學": "亞東科技大學", "馬偕學校財團法人馬偕醫學大學": "馬偕醫學大學", "中信學校財團法人中信金融管理學院": "中信金融管理學院", "南亞科技學校財團法人南亞技術學院": "南亞技術學院", "德育學校財團法人德育護理健康學院": "德育護理健康學院", "法鼓學校財團法人法鼓文理學院": "法鼓文理學院", "馬偕學校財團法人馬偕醫護管理專科學校": "馬偕醫護管理專科學校", "新生學校財團法人新生醫護管理專科學校": "新生醫護管理專科學校", "學校財團法人中華浸信會基督教台灣浸會神學院": "中華浸信會基督教台灣浸會神學院", "台神學校財團法人台灣神學研究學院": "台灣神學研究學院", "基督教華神學校財團法人中華福音神學研究學院": "中華福音神學研究學院", "福智學校財團法人福智佛教學院": "福智佛教學院", "國立臺北科技大學附設進修學院": "國立臺北科技大學", "國立高雄科技大學附設進修學院": "國立高雄科技大學", "國立臺北商業大學附設空中進修學院": "國立臺北商業大學", "國立臺中科技大學附設空中進修學院": "國立臺中科技大學", "嶺東科技大學附設進修學院": "嶺東科技大學", "基督教台灣浸會神學院": "中華浸信會基督教台灣浸會神學院", "中華民國陸軍官校": "陸軍軍官學校", "中華民國海軍官校": "海軍軍官學校", "中華民國空軍官校": "空軍軍官學校"};
export interface SchoolCatalogEntry { name: string; englishName: string; emailRoots: readonly string[]; authority: string }
export const SCHOOL_CATALOG: readonly SchoolCatalogEntry[] = [
  {"name": "國立政治大學", "englishName": "National Chengchi University", "emailRoots": ["nccu.edu.tw"], "authority": "MOE"},
  {"name": "國立清華大學", "englishName": "National Tsing Hua University", "emailRoots": ["nthu.edu.tw"], "authority": "MOE"},
  {"name": "國立臺灣大學", "englishName": "National Taiwan University", "emailRoots": ["ntu.edu.tw"], "authority": "MOE"},
  {"name": "國立臺灣師範大學", "englishName": "National Taiwan Normal University", "emailRoots": ["ntnu.edu.tw"], "authority": "MOE"},
  {"name": "國立成功大學", "englishName": "National Cheng Kung University", "emailRoots": ["ncku.edu.tw"], "authority": "MOE"},
  {"name": "國立中興大學", "englishName": "National Chung Hsing University", "emailRoots": ["nchu.edu.tw"], "authority": "MOE"},
  {"name": "國立陽明交通大學", "englishName": "National Yang Ming Chiao Tung University", "emailRoots": ["nycu.edu.tw"], "authority": "MOE"},
  {"name": "國立中央大學", "englishName": "National Central University", "emailRoots": ["ncu.edu.tw"], "authority": "MOE"},
  {"name": "國立中山大學", "englishName": "National Sun Yat-sen University", "emailRoots": ["nsysu.edu.tw"], "authority": "MOE"},
  {"name": "國立臺灣海洋大學", "englishName": "National Taiwan Ocean University", "emailRoots": ["ntou.edu.tw"], "authority": "MOE"},
  {"name": "國立中正大學", "englishName": "National Chung Cheng University", "emailRoots": ["ccu.edu.tw"], "authority": "MOE"},
  {"name": "國立高雄師範大學", "englishName": "National Kaohsiung Normal University", "emailRoots": ["nknu.edu.tw"], "authority": "MOE"},
  {"name": "國立彰化師範大學", "englishName": "National Changhua University of Education", "emailRoots": ["ncue.edu.tw"], "authority": "MOE"},
  {"name": "國立臺北大學", "englishName": "National Taipei University", "emailRoots": ["ntpu.edu.tw"], "authority": "MOE"},
  {"name": "國立嘉義大學", "englishName": "National Chiayi University", "emailRoots": ["ncyu.edu.tw"], "authority": "MOE"},
  {"name": "國立高雄大學", "englishName": "National University of Kaohsiung", "emailRoots": ["nuk.edu.tw"], "authority": "MOE"},
  {"name": "國立東華大學", "englishName": "National Dong Hwa University", "emailRoots": ["ndhu.edu.tw"], "authority": "MOE"},
  {"name": "國立暨南國際大學", "englishName": "National Chi Nan University", "emailRoots": ["ncnu.edu.tw"], "authority": "MOE"},
  {"name": "國立臺灣科技大學", "englishName": "National Taiwan University of Science and Technology", "emailRoots": ["ntust.edu.tw"], "authority": "MOE"},
  {"name": "國立雲林科技大學", "englishName": "National Yunlin University of Science & Technology", "emailRoots": ["yuntech.edu.tw"], "authority": "MOE"},
  {"name": "國立屏東科技大學", "englishName": "National Pingtung University of Science and Technology", "emailRoots": ["npust.edu.tw"], "authority": "MOE"},
  {"name": "國立臺北科技大學", "englishName": "National Taipei University of Technology", "emailRoots": ["ntut.edu.tw"], "authority": "MOE"},
  {"name": "國立臺北藝術大學", "englishName": "Taipei National University of the Arts", "emailRoots": ["tnua.edu.tw"], "authority": "MOE"},
  {"name": "國立臺灣藝術大學", "englishName": "National Taiwan University of Arts", "emailRoots": ["ntua.edu.tw"], "authority": "MOE"},
  {"name": "國立臺東大學", "englishName": "National Taitung University", "emailRoots": ["nttu.edu.tw"], "authority": "MOE"},
  {"name": "國立宜蘭大學", "englishName": "National Ilan University", "emailRoots": ["niu.edu.tw"], "authority": "MOE"},
  {"name": "國立聯合大學", "englishName": "National United University", "emailRoots": ["nuu.edu.tw"], "authority": "MOE"},
  {"name": "國立虎尾科技大學", "englishName": "National Formosa University", "emailRoots": ["nfu.edu.tw"], "authority": "MOE"},
  {"name": "國立臺南藝術大學", "englishName": "Tainan National University of the Arts", "emailRoots": ["tnnua.edu.tw"], "authority": "MOE"},
  {"name": "國立臺南大學", "englishName": "National University of Tainan", "emailRoots": ["nutn.edu.tw"], "authority": "MOE"},
  {"name": "國立臺北教育大學", "englishName": "National Taipei University of Education", "emailRoots": ["ntue.edu.tw"], "authority": "MOE"},
  {"name": "國立臺中教育大學", "englishName": "National Taichung University of Education", "emailRoots": ["ntcu.edu.tw"], "authority": "MOE"},
  {"name": "國立澎湖科技大學", "englishName": "National Penghu University of Science and Technology", "emailRoots": ["npu.edu.tw"], "authority": "MOE"},
  {"name": "國立勤益科技大學", "englishName": "National Chin-Yi University of Technology", "emailRoots": ["ncut.edu.tw"], "authority": "MOE"},
  {"name": "國立體育大學", "englishName": "National Taiwan Sport University", "emailRoots": ["ntsu.edu.tw"], "authority": "MOE"},
  {"name": "國立臺北護理健康大學", "englishName": "National Taipei University of Nursing and Health Sciences", "emailRoots": ["ntunhs.edu.tw"], "authority": "MOE"},
  {"name": "國立高雄餐旅大學", "englishName": "National Kaohsiung University of Hospitality and Tourism", "emailRoots": ["nkuht.edu.tw"], "authority": "MOE"},
  {"name": "國立金門大學", "englishName": "National Quemoy University", "emailRoots": ["nqu.edu.tw"], "authority": "MOE"},
  {"name": "國立臺灣體育運動大學", "englishName": "National Taiwan University of Sport", "emailRoots": ["ntus.edu.tw"], "authority": "MOE"},
  {"name": "國立臺中科技大學", "englishName": "National  Taichung University Of  Science And Technology", "emailRoots": ["nutc.edu.tw"], "authority": "MOE"},
  {"name": "國立臺北商業大學", "englishName": "National Taipei University of  Business", "emailRoots": ["ntub.edu.tw"], "authority": "MOE"},
  {"name": "國立屏東大學", "englishName": "National Pingtung University", "emailRoots": ["nptu.edu.tw"], "authority": "MOE"},
  {"name": "國立高雄科技大學", "englishName": "National Kaohsiung University of Science and Technology", "emailRoots": ["nkust.edu.tw"], "authority": "MOE"},
  {"name": "國立臺灣戲曲學院", "englishName": "National Taiwan College of Performing Arts", "emailRoots": ["tcpa.edu.tw"], "authority": "MOE"},
  {"name": "國立臺南護理專科學校", "englishName": "National Tainan Junior College of Nursing", "emailRoots": ["ntin.edu.tw"], "authority": "MOE"},
  {"name": "國立臺東專科學校", "englishName": "National Taitung Junior College", "emailRoots": ["ntc.edu.tw"], "authority": "MOE"},
  {"name": "國立空中大學", "englishName": "National Open University", "emailRoots": ["nou.edu.tw"], "authority": "MOE"},
  {"name": "東海大學", "englishName": "Tunghai University", "emailRoots": ["thu.edu.tw"], "authority": "MOE"},
  {"name": "輔仁大學", "englishName": "Fu Jen Catholic University", "emailRoots": ["fju.edu.tw"], "authority": "MOE"},
  {"name": "東吳大學", "englishName": "Soochow University", "emailRoots": ["scu.edu.tw"], "authority": "MOE"},
  {"name": "中原大學", "englishName": "Chung Yuan Christian University", "emailRoots": ["cycu.edu.tw"], "authority": "MOE"},
  {"name": "淡江大學", "englishName": "Tamkang University", "emailRoots": ["tku.edu.tw"], "authority": "MOE"},
  {"name": "中國文化大學", "englishName": "Chinese Culture University", "emailRoots": ["pccu.edu.tw"], "authority": "MOE"},
  {"name": "逢甲大學", "englishName": "Feng Chia University", "emailRoots": ["fcu.edu.tw"], "authority": "MOE"},
  {"name": "靜宜大學", "englishName": "Providence University", "emailRoots": ["pu.edu.tw"], "authority": "MOE"},
  {"name": "長庚大學", "englishName": "Chang Gung University", "emailRoots": ["cgu.edu.tw"], "authority": "MOE"},
  {"name": "元智大學", "englishName": "Yuan Ze University", "emailRoots": ["yzu.edu.tw"], "authority": "MOE"},
  {"name": "中華大學", "englishName": "Chung Hua University", "emailRoots": ["chu.edu.tw"], "authority": "MOE"},
  {"name": "大葉大學", "englishName": "Da-Yeh University", "emailRoots": ["dyu.edu.tw"], "authority": "MOE"},
  {"name": "華梵大學", "englishName": "Huafan University", "emailRoots": ["hfu.edu.tw"], "authority": "MOE"},
  {"name": "義守大學", "englishName": "I-Shou University", "emailRoots": ["isu.edu.tw"], "authority": "MOE"},
  {"name": "世新大學", "englishName": "Shih Hsin University", "emailRoots": ["shu.edu.tw"], "authority": "MOE"},
  {"name": "銘傳大學", "englishName": "Ming Chuan University", "emailRoots": ["mcu.edu.tw"], "authority": "MOE"},
  {"name": "實踐大學", "englishName": "Shih Chien University", "emailRoots": ["usc.edu.tw"], "authority": "MOE"},
  {"name": "朝陽科技大學", "englishName": "Chaoyang University of Technology", "emailRoots": ["cyut.edu.tw"], "authority": "MOE"},
  {"name": "高雄醫學大學", "englishName": "Kaohsiung Medical University", "emailRoots": ["kmu.edu.tw"], "authority": "MOE"},
  {"name": "南華大學", "englishName": "Nanhua university", "emailRoots": ["nhu.edu.tw"], "authority": "MOE"},
  {"name": "真理大學", "englishName": "Aletheia University", "emailRoots": ["au.edu.tw"], "authority": "MOE"},
  {"name": "大同大學", "englishName": "Tatung University", "emailRoots": ["ttu.edu.tw"], "authority": "MOE"},
  {"name": "南臺科技大學", "englishName": "Southern Taiwan University of Science and Technology", "emailRoots": ["stust.edu.tw"], "authority": "MOE"},
  {"name": "崑山科技大學", "englishName": "Kun Shan University", "emailRoots": ["ksu.edu.tw"], "authority": "MOE"},
  {"name": "嘉南藥理大學", "englishName": "Chia Nan University of Pharmacy & Science", "emailRoots": ["cnu.edu.tw"], "authority": "MOE"},
  {"name": "樹德科技大學", "englishName": "Shu-Te University", "emailRoots": ["stu.edu.tw"], "authority": "MOE"},
  {"name": "慈濟大學", "englishName": "Tzu Chi University", "emailRoots": ["tcu.edu.tw"], "authority": "MOE"},
  {"name": "臺北醫學大學", "englishName": "Taipei Medical University", "emailRoots": ["tmu.edu.tw"], "authority": "MOE"},
  {"name": "中山醫學大學", "englishName": "Chung Shan Medical University", "emailRoots": ["csmu.edu.tw"], "authority": "MOE"},
  {"name": "龍華科技大學", "englishName": "Lunghwa University of Science and Technology", "emailRoots": ["lhu.edu.tw"], "authority": "MOE"},
  {"name": "輔英科技大學", "englishName": "Fooyin University", "emailRoots": ["fy.edu.tw"], "authority": "MOE"},
  {"name": "明新科技大學", "englishName": "Minghsin University of Science and Technology", "emailRoots": ["must.edu.tw"], "authority": "MOE"},
  {"name": "長榮大學", "englishName": "Chang Jung Christian University", "emailRoots": ["cjcu.edu.tw"], "authority": "MOE"},
  {"name": "弘光科技大學", "englishName": "Hungkuang University", "emailRoots": ["hk.edu.tw"], "authority": "MOE"},
  {"name": "中國醫藥大學", "englishName": "China Medical University", "emailRoots": ["cmu.edu.tw"], "authority": "MOE"},
  {"name": "健行科技大學", "englishName": "Chien Hsin University of Science and Technology", "emailRoots": ["uch.edu.tw"], "authority": "MOE"},
  {"name": "正修科技大學", "englishName": "Cheng Shiu University", "emailRoots": ["csu.edu.tw"], "authority": "MOE"},
  {"name": "萬能科技大學", "englishName": "Vanung University", "emailRoots": ["vnu.edu.tw"], "authority": "MOE"},
  {"name": "玄奘大學", "englishName": "Hsuan Chuang University", "emailRoots": ["hcu.edu.tw"], "authority": "MOE"},
  {"name": "建國科技大學", "englishName": "Chienkuo Technology University", "emailRoots": ["ctu.edu.tw"], "authority": "MOE"},
  {"name": "明志科技大學", "englishName": "Ming Chi University of Technology", "emailRoots": ["mcut.edu.tw"], "authority": "MOE"},
  {"name": "台鋼科技大學", "englishName": "Taiwan Steel University of Science and Technology", "emailRoots": ["tsust.edu.tw"], "authority": "MOE"},
  {"name": "大仁科技大學", "englishName": "Tajen University", "emailRoots": ["tajen.edu.tw"], "authority": "MOE"},
  {"name": "聖約翰科技大學", "englishName": "St. John’s University", "emailRoots": ["sju.edu.tw"], "authority": "MOE"},
  {"name": "嶺東科技大學", "englishName": "Ling Tung University", "emailRoots": ["ltu.edu.tw"], "authority": "MOE"},
  {"name": "中國科技大學", "englishName": "China University of Technology", "emailRoots": ["cute.edu.tw"], "authority": "MOE"},
  {"name": "中臺科技大學", "englishName": "Central Taiwan University of Science and Technology", "emailRoots": ["ctust.edu.tw"], "authority": "MOE"},
  {"name": "亞洲大學", "englishName": "Asia University", "emailRoots": ["asia.edu.tw"], "authority": "MOE"},
  {"name": "開南大學", "englishName": "Kainan University", "emailRoots": ["knu.edu.tw"], "authority": "MOE"},
  {"name": "佛光大學", "englishName": "Fo Guang University", "emailRoots": ["fgu.edu.tw"], "authority": "MOE"},
  {"name": "台南應用科技大學", "englishName": "Tainan University of Technology", "emailRoots": ["tut.edu.tw"], "authority": "MOE"},
  {"name": "中信科技大學", "englishName": "CTBC UNIVERSITY OF TECHNOLOGY", "emailRoots": ["ctbctech.edu.tw", "feu.edu.tw"], "authority": "MOE"},
  {"name": "元培醫事科技大學", "englishName": "Yuanpei University of Medical Technology", "emailRoots": ["ypu.edu.tw"], "authority": "MOE"},
  {"name": "景文科技大學", "englishName": "Jinwen University of Science and Technology", "emailRoots": ["just.edu.tw"], "authority": "MOE"},
  {"name": "中華醫事科技大學", "englishName": "Chung Hwa University of Medical Technology", "emailRoots": ["hwai.edu.tw"], "authority": "MOE"},
  {"name": "東南科技大學", "englishName": "Tungnan University", "emailRoots": ["tnu.edu.tw"], "authority": "MOE"},
  {"name": "德明財經科技大學", "englishName": "Takming University of Science and Technology", "emailRoots": ["takming.edu.tw"], "authority": "MOE"},
  {"name": "南開科技大學", "englishName": "Nan Kai University of Technology", "emailRoots": ["nkut.edu.tw"], "authority": "MOE"},
  {"name": "中華科技大學", "englishName": "China University of Science and Technology", "emailRoots": ["cust.edu.tw"], "authority": "MOE"},
  {"name": "僑光科技大學", "englishName": "Overseas Chinese University", "emailRoots": ["ocu.edu.tw"], "authority": "MOE"},
  {"name": "育達科技大學", "englishName": "Yu Da University of Science and Technology", "emailRoots": ["ydu.edu.tw"], "authority": "MOE"},
  {"name": "美和科技大學", "englishName": "Meiho University", "emailRoots": ["meiho.edu.tw"], "authority": "MOE"},
  {"name": "吳鳳科技大學", "englishName": "WuFeng University", "emailRoots": ["wfu.edu.tw"], "authority": "MOE"},
  {"name": "修平科技大學", "englishName": "Hsiuping University of Science and Technology", "emailRoots": ["hust.edu.tw"], "authority": "MOE"},
  {"name": "長庚科技大學", "englishName": "Chang Gung University of Science and Technology", "emailRoots": ["cgust.edu.tw"], "authority": "MOE"},
  {"name": "臺北城市科技大學", "englishName": "Taipei City University of Science and Technology", "emailRoots": ["tpcu.edu.tw"], "authority": "MOE"},
  {"name": "敏實科技大學", "englishName": "Minth University of Science and Technology", "emailRoots": ["mitust.edu.tw"], "authority": "MOE"},
  {"name": "醒吾科技大學", "englishName": "Hsing Wu University of Science and Technology", "emailRoots": ["hwu.edu.tw"], "authority": "MOE"},
  {"name": "文藻外語大學", "englishName": "Wenzao Ursuline University of Languages", "emailRoots": ["wzu.edu.tw"], "authority": "MOE"},
  {"name": "華夏科技大學", "englishName": "Hwa Hsia University of Technology", "emailRoots": ["hwh.edu.tw"], "authority": "MOE"},
  {"name": "致理科技大學", "englishName": "Chihlee University of Technology", "emailRoots": ["chihlee.edu.tw"], "authority": "MOE"},
  {"name": "康寧大學", "englishName": "University of Kang Ning", "emailRoots": ["ukn.edu.tw"], "authority": "MOE"},
  {"name": "宏國德霖科技大學", "englishName": "Hungkuo Delin University of Technology", "emailRoots": ["hdut.edu.tw"], "authority": "MOE"},
  {"name": "崇右影藝科技大學", "englishName": "Chungyu University of Film and Arts", "emailRoots": ["cufa.edu.tw"], "authority": "MOE"},
  {"name": "台北海洋科技大學", "englishName": "Taipei University of Marine Technology", "emailRoots": ["tumt.edu.tw"], "authority": "MOE"},
  {"name": "亞東科技大學", "englishName": "Asia Eastern University of Science and Technology", "emailRoots": ["aeust.edu.tw"], "authority": "MOE"},
  {"name": "馬偕醫學大學", "englishName": "MacKay Medical University", "emailRoots": ["mmu.edu.tw"], "authority": "MOE"},
  {"name": "中信金融管理學院", "englishName": "CTBC Business School", "emailRoots": ["ctbc.edu.tw"], "authority": "MOE"},
  {"name": "南亞技術學院", "englishName": "Nanya Institute of Technology", "emailRoots": ["nanya.edu.tw"], "authority": "MOE"},
  {"name": "黎明技術學院", "englishName": "Lee-Ming Institute of Technology", "emailRoots": ["lit.edu.tw"], "authority": "MOE"},
  {"name": "德育護理健康學院", "englishName": "Deh Yu College of Nursing and Health", "emailRoots": ["dyhu.edu.tw"], "authority": "MOE"},
  {"name": "法鼓文理學院", "englishName": "Dharma Drum Institute of Liberal Art", "emailRoots": ["dila.edu.tw"], "authority": "MOE"},
  {"name": "馬偕醫護管理專科學校", "englishName": "MacKay Junior College of Medicine, Nursing, and Management", "emailRoots": ["mkc.edu.tw"], "authority": "MOE"},
  {"name": "仁德醫護管理專科學校", "englishName": "Jen-Teh Junior College of Medicine, Nursing and Management", "emailRoots": ["jente.edu.tw"], "authority": "MOE"},
  {"name": "樹人醫護管理專科學校", "englishName": "Shu-Zen Junior College of Medicine and Management", "emailRoots": ["szmc.edu.tw"], "authority": "MOE"},
  {"name": "慈惠醫護管理專科學校", "englishName": "TZU HUI Institute of Technology", "emailRoots": ["tzuhui.edu.tw"], "authority": "MOE"},
  {"name": "耕莘健康管理專科學校", "englishName": "Cardinal Tien Junior College of Healthcare And Management", "emailRoots": ["ctcn.edu.tw"], "authority": "MOE"},
  {"name": "敏惠醫護管理專科學校", "englishName": "Min-Hwei Junior College of Health Care Management", "emailRoots": ["mhchcm.edu.tw"], "authority": "MOE"},
  {"name": "育英醫護管理專科學校", "englishName": "Yuh-Ing Junior College of Health Care & Management", "emailRoots": ["yuhing.edu.tw"], "authority": "MOE"},
  {"name": "聖母醫護管理專科學校", "englishName": "St. Mary''s Junior College of Medicine, Nursing and Management", "emailRoots": ["smc.edu.tw"], "authority": "MOE"},
  {"name": "新生醫護管理專科學校", "englishName": "Hsin Sheng Junior College of Medical Care and Management", "emailRoots": ["hsc.edu.tw"], "authority": "MOE"},
  {"name": "崇仁醫護管理專科學校", "englishName": "Chung-Jen Junior College of Nursing, Health Sciences and Management", "emailRoots": ["cjc.edu.tw"], "authority": "MOE"},
  {"name": "中華浸信會基督教台灣浸會神學院", "englishName": "Taiwan Baptist Christian Seminary", "emailRoots": ["tbts.edu.tw"], "authority": "MOE"},
  {"name": "臺北基督學院", "englishName": "Christ''s College Taipei", "emailRoots": ["cct.edu.tw"], "authority": "MOE"},
  {"name": "台灣神學研究學院", "englishName": "Taiwan Graduate School of Theology", "emailRoots": ["tgst.edu.tw"], "authority": "MOE"},
  {"name": "一貫道崇德學院", "englishName": "I.K.T. Chong-De School", "emailRoots": [], "authority": "MOE"},
  {"name": "台灣基督長老教會南神神學院", "englishName": "Tainan Theological College", "emailRoots": ["ttcs.edu.tw"], "authority": "MOE"},
  {"name": "中華福音神學研究學院", "englishName": "China Evangelical Graduate School of Theology", "emailRoots": ["ces.org.tw"], "authority": "MOE"},
  {"name": "唯心聖教學院", "englishName": "Weixin Shengjiao College", "emailRoots": ["wxsjc.edu.tw"], "authority": "MOE"},
  {"name": "福智佛教學院", "englishName": "Bliss and Wisdom Buddhist College", "emailRoots": ["bwbc.edu.tw"], "authority": "MOE"},
  {"name": "臺北市立大學", "englishName": "University of Taipei", "emailRoots": ["utaipei.edu.tw"], "authority": "MOE"},
  {"name": "高雄市立空中大學", "englishName": "Open University of Kaohsiung", "emailRoots": ["ouk.edu.tw"], "authority": "MOE"},
  {"name": "國防醫學大學", "englishName": "", "emailRoots": ["ndmutsgh.edu.tw", "ndmctsgh.edu.tw"], "authority": "MND"},
  {"name": "國防大學", "englishName": "", "emailRoots": ["ndu.edu.tw"], "authority": "MND"},
  {"name": "中央警察大學", "englishName": "", "emailRoots": ["cpu.edu.tw"], "authority": "MOI"},
  {"name": "陸軍軍官學校", "englishName": "", "emailRoots": [], "authority": "MND"},
  {"name": "陸軍專科學校", "englishName": "", "emailRoots": [], "authority": "MND"},
  {"name": "海軍軍官學校", "englishName": "", "emailRoots": [], "authority": "MND"},
  {"name": "空軍軍官學校", "englishName": "", "emailRoots": [], "authority": "MND"},
  {"name": "空軍航空技術學院", "englishName": "", "emailRoots": [], "authority": "MND"},
  {"name": "臺灣警察專科學校", "englishName": "Taiwan Police College", "emailRoots": ["tpa.edu.tw"], "authority": "MOI"},
];
