"""Generate the shared picker/domain tables from the reviewed, source-attributed catalog.
No network requests. Updating emailRoots requires evidence, not a guessed website hostname.
"""
import argparse, json
from pathlib import Path
root = Path(__file__).resolve().parent.parent
catalog = json.loads((root / 'packages/shared/data/taiwan-school-catalog.json').read_text())
parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
q = lambda value: json.dumps(value, ensure_ascii=False)
names = [s['name'] for s in catalog['schools']]
roster = catalog['rosterVerification']
assert len(names) == len(set(names))
assert len(roster['entries']) == len({r['code'] for r in roster['entries']})
assert set(names) == {r['institution'] for r in roster['entries']}
for entry in roster['entries']:
    assert entry['name'] == entry['institution'] or catalog['aliases'].get(entry['name']) == entry['institution']
for school in catalog['schools']:
    assert not school['emailRoots'] or school['emailEvidence']
    assert not any(d in ['gmail.com', 'mail.mil.tw', 'edu.tw'] for d in school['emailRoots'])
files = {
 'packages/shared/src/taiwanUniversities.ts': '/** Generated by scripts/generate-school-catalog.py. See data/taiwan-school-catalog.json for sources. */\nexport const TAIWAN_UNIVERSITIES = [\n' + ''.join('  '+q(n)+',\n' for n in names+['其他']) + '] as const;\nexport type TaiwanUniversity = (typeof TAIWAN_UNIVERSITIES)[number];\n',
 'packages/shared/src/taiwanSchoolCatalog.ts': '''/** Generated from the reviewed catalog; never derive email authority from a website alone. */
export const SCHOOL_CATALOG_VERIFIED_AT = ''' + q(roster['retrievedAt']) + ''';
export const SCHOOL_CATALOG_ACADEMIC_YEAR = ''' + str(roster['academicYear']) + ''';
export const SCHOOL_CATALOG_SOURCE = ''' + q(roster['announcement']) + ''';
export const SCHOOL_NAME_ALIASES: Readonly<Record<string, string>> = ''' + q(catalog['aliases']) + ''';
export interface SchoolCatalogEntry { name: string; englishName: string; emailRoots: readonly string[]; authority: string }
export const SCHOOL_CATALOG: readonly SchoolCatalogEntry[] = [
''' + ''.join('  '+q({k:s[k] for k in ['name','englishName','emailRoots','authority']})+',\n' for s in catalog['schools']) + '];\n'
}
for name, content in files.items():
    path = root / name
    if args.check:
        if not path.exists() or path.read_text() != content: raise SystemExit(f'Regenerate {name}')
    else: path.write_text(content)
print(f"School catalog: {len(names)} unique institutions; all {len(roster['entries'])} official {roster['academicYear']} roster entries mapped.")
