/**
 * Seeds hand-authored TestCase rows for the local (Vercel Sandbox) judge pilot: the 5 easiest
 * CPE-49 problems. Each problem gets its existing Sample row (already correct — it's the official
 * statement's own example) plus one boundary-case block covering edges the sample doesn't:
 *
 *   - uva-100:   n=1 (trivial single-cycle case), a reversed pair, and a near-upper-bound range.
 *   - uva-10041: single relative (sum=0), all-same-address (sum=0), and the widest legal address gap.
 *   - uva-10055: equal inputs (diff=0) and values right at the documented 2^32 bound.
 *   - uva-10035: bare "0 0" terminator with no data lines — expects truly empty output.
 *   - uva-10929: shortest possible multiple ("11") and two ~1000-digit numbers straddling the
 *                documented max length, one a multiple and one not (exercises both branches at
 *                the boundary the problem statement actually allows).
 *
 * Every expected output here was generated by compiling and running a hand-verified reference
 * solution locally (not hand-calculated) after first confirming that same solution reproduces the
 * *official* sample output exactly — see the commit this script shipped in for that verification
 * trail. Safe to re-run: replaces this problem's TestCase rows each time.
 */
import { prisma } from "@oj/db";
import { seedFromSample } from "./testcase-seed-helper.js";

const NINES_998 = "9".repeat(998); // even count -> alternating sum cancels to 0 -> multiple of 11
const NINES_999 = "9".repeat(999); // odd count -> alternating sum leaves one unpaired 9 -> not a multiple

async function main() {
  await seedFromSample("uva-100-the-3n-1-problem", [
    { input: "1 1\n10 1\n1 9999\n", output: "1 1 1\n10 1 20\n1 9999 262\n" },
  ]);

  await seedFromSample("uva-10041-vito-s-family", [
    { input: "4\n1 500\n4 100 100 100 100\n2 1 29999\n5 1 3 6 9 11\n", output: "0\n0\n29998\n16\n" },
  ]);

  await seedFromSample("uva-10055-hashmat", [
    { input: "5 5\n4294967295 0\n0 4294967295\n1 0\n", output: "0\n4294967295\n4294967295\n1\n" },
  ]);

  await seedFromSample("uva-10035-primary-arithmetic", [{ input: "0 0\n", output: "" }]);

  await seedFromSample("uva-10929-you-can-say-11", [
    {
      input: `11\n99\n${NINES_998}\n${NINES_999}\n0\n`,
      output: `11 is a multiple of 11.\n99 is a multiple of 11.\n${NINES_998} is a multiple of 11.\n${NINES_999} is not a multiple of 11.\n`,
    },
  ]);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
